function scopecam_alignvideo( obj, session, trial )
    pScopeAlign = ml_cai_scopecam_alignvideo( ...
        trial.getTrialDirectory(), 'outputFolder', trial.getAnalysisDirectory(), ...
        'spatialDownsampling', obj.Config.miniscope_camera.spatial_downsampling, ...
        'isNonRigid', obj.Config.miniscope_camera.use_nonrigid_alignment==1, ...
        'verbose', obj.isVerbose() );

    save(fullfile(trial.getAnalysisDirectory(), 'pScopeAlign'), 'pScopeAlign');
end